
/* MACHINE GENERATED By Halide. */

#include <assert.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

void halide_unused(bool e){};

/*@
pure int max(int x, int y) = x > y ? x : y;

pure int min(int x, int y) = x > y ? y : x;

pure float max(float x, float y) = x > y ? x : y;

pure float min(float x, float y) = x > y ? y : x;

pure int abs(int x) = x >= 0 ? x : -x;

pure float abs(float x) = x >= 0 ? x : -x;

// Euclidean division is defined internally in VerCors
pure int euclidean_div(int x, int y);
pure int euclidean_mod(int x, int y);
pure int hdiv(int x, int y) = y == 0 ? 0 : euclidean_div(x, y);
pure int hmod(int x, int y) = y == 0 ? 0 : euclidean_mod(x, y);
@*/

/*@
  requires y != 0;
  ensures \result == euclidean_div(x, y);
@*/
/*inline*/ int /*@ pure @*/ div_eucl(int x, int y)
{
    int q = x/y;
    int r = x%y;
    return r < 0 ? q + (y > 0 ? -1 : 1) : q;
}

/*@
  requires y != 0;
  ensures \result == euclidean_mod(x, y);
@*/
/*inline*/ int /*@ pure @*/ mod_eucl(int x, int y)
{
    int r = x%y;
    return (x >= 0 || r == 0) ? r : r + abs(y);
}

static inline float /*@ pure @*/ fast_inverse_f32(float x) {return 1.0f/x;};
//@ given double eps;
static inline float /*@ pure @*/ sqrt_f32(double x) {return (float)sqrt((double)x)/*@given {eps=eps}@*/;}
static inline float /*@ pure @*/ pow_f32(float x, float y){ return (float) pow((double) x, (double) y);}
static inline float /*@ pure @*/ floor_f32(float x){ return (float) floor((double) x); }
static inline float /*@ pure @*/ ceil_f32(float x){ return (float) ceil((double) x); }
static inline float /*@ pure @*/ round_f32(float x){ return (float) round((double) x); }

//@ given double eps;
static inline double /*@ pure @*/ sqrt_f64(double x) {return sqrt(x)/*@given {eps=eps}@*/;}
static inline double /*@ pure @*/ pow_f64(double x, double y) {return pow(x, y);}
static inline double /*@ pure @*/ floor_f64(double x) {return floor(x);}
static inline double /*@ pure @*/ ceil_f64(double x) {return ceil(x);}
static inline double /*@ pure @*/ round_f64(double x){ return round(x); }



struct halide_dimension_t {
    int32_t min, extent, stride;
};

struct halide_buffer_uint16_t {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    uint16_t *host;
};

/*@ 
 requires buf != NULL ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ uint16_t *_halide_buffer_get_host_uint16_t(struct halide_buffer_uint16_t *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_min_uint16_t(struct halide_buffer_uint16_t *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_max_uint16_t(struct halide_buffer_uint16_t *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_extent_uint16_t(struct halide_buffer_uint16_t *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_stride_uint16_t(struct halide_buffer_uint16_t *buf, int d) {
    return buf->dim[d].stride;
}
struct halide_buffer_float {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    float *host;
};

/*@ 
 requires buf != NULL ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ float *_halide_buffer_get_host_float(struct halide_buffer_float *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_min_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_max_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_extent_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_stride_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].stride;
}
struct halide_buffer_uint8_t {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    uint8_t *host;
};

/*@ 
 requires buf != NULL ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ uint8_t *_halide_buffer_get_host_uint8_t(struct halide_buffer_uint8_t *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_min_uint8_t(struct halide_buffer_uint8_t *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_max_uint8_t(struct halide_buffer_uint8_t *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_extent_uint8_t(struct halide_buffer_uint8_t *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ int _halide_buffer_get_stride_uint8_t(struct halide_buffer_uint8_t *buf, int d) {
    return buf->dim[d].stride;
}
//@ pure int pure_input(int x);
//@ pure float pure_matrix_3200(int x);
//@ pure float pure_matrix_7000(int x);
//@ pure int pure_processed(int x);



#ifdef __cplusplus
extern "C" {
#endif

/*@
 context _input_buffer != NULL ** Perm(_input_buffer, 1\2);
 context Perm(_input_buffer->dim, 1\2) ** _input_buffer->dim != NULL;
 context \pointer_length(_input_buffer->dim) == 2;
 context Perm(_input_buffer->host, 1\2) ** _input_buffer->host != NULL;
 context Perm(&_input_buffer->dim[0], 1\2);
 context Perm(_input_buffer->dim[0].min, 1\2) ** Perm(_input_buffer->dim[0].stride, 1\2) ** Perm(_input_buffer->dim[0].extent, 1\2);
 context Perm(&_input_buffer->dim[1], 1\2);
 context Perm(_input_buffer->dim[1].min, 1\2) ** Perm(_input_buffer->dim[1].stride, 1\2) ** Perm(_input_buffer->dim[1].extent, 1\2);
 context \pointer_length(_input_buffer->host) == 1 + abs(_input_buffer->dim[0].stride) * (_input_buffer->dim[0].extent - 1) + abs(_input_buffer->dim[1].stride) * (_input_buffer->dim[1].extent - 1);
 context _matrix_3200_buffer != NULL ** Perm(_matrix_3200_buffer, 1\2);
 context Perm(_matrix_3200_buffer->dim, 1\2) ** _matrix_3200_buffer->dim != NULL;
 context \pointer_length(_matrix_3200_buffer->dim) == 2;
 context Perm(_matrix_3200_buffer->host, 1\2) ** _matrix_3200_buffer->host != NULL;
 context Perm(&_matrix_3200_buffer->dim[0], 1\2);
 context Perm(_matrix_3200_buffer->dim[0].min, 1\2) ** Perm(_matrix_3200_buffer->dim[0].stride, 1\2) ** Perm(_matrix_3200_buffer->dim[0].extent, 1\2);
 context Perm(&_matrix_3200_buffer->dim[1], 1\2);
 context Perm(_matrix_3200_buffer->dim[1].min, 1\2) ** Perm(_matrix_3200_buffer->dim[1].stride, 1\2) ** Perm(_matrix_3200_buffer->dim[1].extent, 1\2);
 context \pointer_length(_matrix_3200_buffer->host) == 1 + abs(_matrix_3200_buffer->dim[0].stride) * (_matrix_3200_buffer->dim[0].extent - 1) + abs(_matrix_3200_buffer->dim[1].stride) * (_matrix_3200_buffer->dim[1].extent - 1);
 context _matrix_7000_buffer != NULL ** Perm(_matrix_7000_buffer, 1\2);
 context Perm(_matrix_7000_buffer->dim, 1\2) ** _matrix_7000_buffer->dim != NULL;
 context \pointer_length(_matrix_7000_buffer->dim) == 2;
 context Perm(_matrix_7000_buffer->host, 1\2) ** _matrix_7000_buffer->host != NULL;
 context Perm(&_matrix_7000_buffer->dim[0], 1\2);
 context Perm(_matrix_7000_buffer->dim[0].min, 1\2) ** Perm(_matrix_7000_buffer->dim[0].stride, 1\2) ** Perm(_matrix_7000_buffer->dim[0].extent, 1\2);
 context Perm(&_matrix_7000_buffer->dim[1], 1\2);
 context Perm(_matrix_7000_buffer->dim[1].min, 1\2) ** Perm(_matrix_7000_buffer->dim[1].stride, 1\2) ** Perm(_matrix_7000_buffer->dim[1].extent, 1\2);
 context \pointer_length(_matrix_7000_buffer->host) == 1 + abs(_matrix_7000_buffer->dim[0].stride) * (_matrix_7000_buffer->dim[0].extent - 1) + abs(_matrix_7000_buffer->dim[1].stride) * (_matrix_7000_buffer->dim[1].extent - 1);
 context _processed_buffer != NULL ** Perm(_processed_buffer, 1\2);
 context Perm(_processed_buffer->dim, 1\2) ** _processed_buffer->dim != NULL;
 context \pointer_length(_processed_buffer->dim) == 3;
 context Perm(_processed_buffer->host, 1\2) ** _processed_buffer->host != NULL;
 context Perm(&_processed_buffer->dim[0], 1\2);
 context Perm(_processed_buffer->dim[0].min, 1\2) ** Perm(_processed_buffer->dim[0].stride, 1\2) ** Perm(_processed_buffer->dim[0].extent, 1\2);
 context Perm(&_processed_buffer->dim[1], 1\2);
 context Perm(_processed_buffer->dim[1].min, 1\2) ** Perm(_processed_buffer->dim[1].stride, 1\2) ** Perm(_processed_buffer->dim[1].extent, 1\2);
 context Perm(&_processed_buffer->dim[2], 1\2);
 context Perm(_processed_buffer->dim[2].min, 1\2) ** Perm(_processed_buffer->dim[2].stride, 1\2) ** Perm(_processed_buffer->dim[2].extent, 1\2);
 context \pointer_length(_processed_buffer->host) == 1 + abs(_processed_buffer->dim[0].stride) * (_processed_buffer->dim[0].extent - 1) + abs(_processed_buffer->dim[1].stride) * (_processed_buffer->dim[1].extent - 1) + abs(_processed_buffer->dim[2].stride) * (_processed_buffer->dim[2].extent - 1);
 context _matrix_7000_buffer->host != _matrix_3200_buffer->host;
 context _processed_buffer->host != _input_buffer->host;
 context ((_input_buffer->dim[0].min == 0) && (_input_buffer->dim[0].extent == 2592)) && (_input_buffer->dim[0].stride == 1);
 context ((_input_buffer->dim[1].min == 0) && (_input_buffer->dim[1].extent == 1968)) && (_input_buffer->dim[1].stride == 2592);
 context (\forall* int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); Perm(&_input_buffer->host[(_1*2592) + _0], 1\2));
 context (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input_buffer->host[(_1*2592) + _0] == pure_input((_1*2592) + _0));
 context ((_matrix_3200_buffer->dim[0].min == 0) && (_matrix_3200_buffer->dim[0].extent == 4)) && (_matrix_3200_buffer->dim[0].stride == 1);
 context ((_matrix_3200_buffer->dim[1].min == 0) && (_matrix_3200_buffer->dim[1].extent == 3)) && (_matrix_3200_buffer->dim[1].stride == 4);
 context (\forall* int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); Perm(&_matrix_3200_buffer->host[(_1*4) + _0], 1\2));
 context (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_3200_buffer->host[(_1*4) + _0] == pure_matrix_3200((_1*4) + _0));
 context ((_matrix_7000_buffer->dim[0].min == 0) && (_matrix_7000_buffer->dim[0].extent == 4)) && (_matrix_7000_buffer->dim[0].stride == 1);
 context ((_matrix_7000_buffer->dim[1].min == 0) && (_matrix_7000_buffer->dim[1].extent == 3)) && (_matrix_7000_buffer->dim[1].stride == 4);
 context (\forall* int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); Perm(&_matrix_7000_buffer->host[(_1*4) + _0], 1\2));
 context (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_7000_buffer->host[(_1*4) + _0] == pure_matrix_7000((_1*4) + _0));
 context ((_processed_buffer->dim[0].min == 0) && (_processed_buffer->dim[0].extent == 2560)) && (_processed_buffer->dim[0].stride == 1);
 context ((_processed_buffer->dim[1].min == 0) && (_processed_buffer->dim[1].extent == 1920)) && (_processed_buffer->dim[1].stride == 2560);
 context ((_processed_buffer->dim[2].min == 0) && (_processed_buffer->dim[2].extent == 3)) && (_processed_buffer->dim[2].stride == 4915200);
 context (\forall* int _0, int _1, int _2; (((((0 <= _0) && (_0 < 2560)) && (0 <= _1)) && (_1 < 1920)) && (0 <= _2)) && (_2 < 3); Perm(&_processed_buffer->host[(_2*4915200) + ((_1*2560) + _0)], 1\1));
@*/
int camera_pipe_mem(struct halide_buffer_uint16_t *_input_buffer, struct halide_buffer_float *_matrix_3200_buffer, struct halide_buffer_float *_matrix_7000_buffer, struct halide_buffer_uint8_t *_processed_buffer) {
 uint16_t* _input = _halide_buffer_get_host_uint16_t(_input_buffer);
 int32_t _input_min_0 = _halide_buffer_get_min_uint16_t(_input_buffer, 0);
 int32_t _input_extent_0 = _halide_buffer_get_extent_uint16_t(_input_buffer, 0);
 int32_t _input_stride_0 = _halide_buffer_get_stride_uint16_t(_input_buffer, 0);
 int32_t _input_min_1 = _halide_buffer_get_min_uint16_t(_input_buffer, 1);
 int32_t _input_extent_1 = _halide_buffer_get_extent_uint16_t(_input_buffer, 1);
 int32_t _input_stride_1 = _halide_buffer_get_stride_uint16_t(_input_buffer, 1);
 float* _matrix_3200 = _halide_buffer_get_host_float(_matrix_3200_buffer);
 int32_t _matrix_3200_min_0 = _halide_buffer_get_min_float(_matrix_3200_buffer, 0);
 int32_t _matrix_3200_extent_0 = _halide_buffer_get_extent_float(_matrix_3200_buffer, 0);
 int32_t _matrix_3200_stride_0 = _halide_buffer_get_stride_float(_matrix_3200_buffer, 0);
 int32_t _matrix_3200_min_1 = _halide_buffer_get_min_float(_matrix_3200_buffer, 1);
 int32_t _matrix_3200_extent_1 = _halide_buffer_get_extent_float(_matrix_3200_buffer, 1);
 int32_t _matrix_3200_stride_1 = _halide_buffer_get_stride_float(_matrix_3200_buffer, 1);
 float* _matrix_7000 = _halide_buffer_get_host_float(_matrix_7000_buffer);
 int32_t _matrix_7000_min_0 = _halide_buffer_get_min_float(_matrix_7000_buffer, 0);
 int32_t _matrix_7000_extent_0 = _halide_buffer_get_extent_float(_matrix_7000_buffer, 0);
 int32_t _matrix_7000_stride_0 = _halide_buffer_get_stride_float(_matrix_7000_buffer, 0);
 int32_t _matrix_7000_min_1 = _halide_buffer_get_min_float(_matrix_7000_buffer, 1);
 int32_t _matrix_7000_extent_1 = _halide_buffer_get_extent_float(_matrix_7000_buffer, 1);
 int32_t _matrix_7000_stride_1 = _halide_buffer_get_stride_float(_matrix_7000_buffer, 1);
 uint8_t* _processed = _halide_buffer_get_host_uint8_t(_processed_buffer);
 int32_t _processed_min_0 = _halide_buffer_get_min_uint8_t(_processed_buffer, 0);
 int32_t _processed_extent_0 = _halide_buffer_get_extent_uint8_t(_processed_buffer, 0);
 int32_t _processed_stride_0 = _halide_buffer_get_stride_uint8_t(_processed_buffer, 0);
 int32_t _processed_min_1 = _halide_buffer_get_min_uint8_t(_processed_buffer, 1);
 int32_t _processed_extent_1 = _halide_buffer_get_extent_uint8_t(_processed_buffer, 1);
 int32_t _processed_stride_1 = _halide_buffer_get_stride_uint8_t(_processed_buffer, 1);
 int32_t _processed_min_2 = _halide_buffer_get_min_uint8_t(_processed_buffer, 2);
 int32_t _processed_extent_2 = _halide_buffer_get_extent_uint8_t(_processed_buffer, 2);
 int32_t _processed_stride_2 = _halide_buffer_get_stride_uint8_t(_processed_buffer, 2);
 halide_unused((_input_stride_0 == 1));
 halide_unused((_input_min_0 == 0));
 halide_unused((_input_extent_0 == 2592));
 halide_unused((_input_stride_1 == 2592));
 halide_unused((_input_min_1 == 0));
 halide_unused((_input_extent_1 == 1968));
 halide_unused((_matrix_3200_stride_0 == 1));
 halide_unused((_matrix_3200_min_0 == 0));
 halide_unused((_matrix_3200_extent_0 == 4));
 halide_unused((_matrix_3200_stride_1 == 4));
 halide_unused((_matrix_3200_min_1 == 0));
 halide_unused((_matrix_3200_extent_1 == 3));
 halide_unused((_matrix_7000_stride_0 == 1));
 halide_unused((_matrix_7000_min_0 == 0));
 halide_unused((_matrix_7000_extent_0 == 4));
 halide_unused((_matrix_7000_stride_1 == 4));
 halide_unused((_matrix_7000_min_1 == 0));
 halide_unused((_matrix_7000_extent_1 == 3));
 halide_unused((_processed_stride_0 == 1));
 halide_unused((_processed_min_0 == 0));
 halide_unused((_processed_extent_0 == 2560));
 halide_unused((_processed_stride_1 == 2560));
 halide_unused((_processed_min_1 == 0));
 halide_unused((_processed_extent_1 == 1920));
 halide_unused((_processed_stride_2 == 4915200));
 halide_unused((_processed_min_2 == 0));
 halide_unused((_processed_extent_2 == 3));
 {
  uint8_t _curve[1024];
  // produce curve
  /*@
   loop_invariant 0 <= _curve_s0_v0 && _curve_s0_v0 <= 0 + 1024;
   loop_invariant (\forall* int _curve_s0_v0_forall; (0 <= _curve_s0_v0_forall) && (_curve_s0_v0_forall < 1024); Perm(&_curve[_curve_s0_v0_forall], 1\1));
  @*/
  for (int _curve_s0_v0 = 0; _curve_s0_v0 < 0 + 1024; _curve_s0_v0++)
  {
   float _4 = (float)((_curve_s0_v0 + -25));
   float _5 = (_4 * 0.001002)<1.000000 ? (_4 * 0.001002) : 1.000000;
   float _6 = _5>0.000000 ? _5 : 0.000000;
   float _t1568 = pow_f32(_6, 0.500000);
   float _7 = (((0.500000 < _t1568) ? (0.414214 - (((1.000000 - _t1568) * ((_t1568 * -0.828427) + 0.828427)) + (_t1568 * -0.585786))) : (((_t1568 * _t1568) * 0.828427) + (_t1568 * 0.585786))) * 255.000000)<254.500000 ? (((0.500000 < _t1568) ? (0.414214 - (((1.000000 - _t1568) * ((_t1568 * -0.828427) + 0.828427)) + (_t1568 * -0.585786))) : (((_t1568 * _t1568) * 0.828427) + (_t1568 * 0.585786))) * 255.000000) : 254.500000;
   float _8 = _7>-0.500000 ? _7 : -0.500000;
   uint8_t _9 = (uint8_t)((_8 + 0.500000));
   _curve[_curve_s0_v0] = ((25 < _curve_s0_v0) ? _9 : 0);
  } // for _curve_s0_v0
  {
   int16_t _f26[12];
   // produce f26
   /*@
    loop_invariant 0 <= _f26_s0_v1 && _f26_s0_v1 <= 0 + 3;
    loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 4)) && ((0 <= _1) && (_1 < 3)); Perm(&_matrix_3200[(_1*4) + _0], 1\2));
    loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_3200[(_1*4) + _0] == pure_matrix_3200((_1*4) + _0));
    loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 4)) && ((0 <= _1) && (_1 < 3)); Perm(&_matrix_7000[(_1*4) + _0], 1\2));
    loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_7000[(_1*4) + _0] == pure_matrix_7000((_1*4) + _0));
    loop_invariant (\forall* int _f26_s0_v0_forall, int _f26_s0_v1_forall; (((0 <= _f26_s0_v1_forall) && (_f26_s0_v1_forall < 3)) && (0 <= _f26_s0_v0_forall)) && (_f26_s0_v0_forall < 4); Perm(&_f26[(_f26_s0_v1_forall*4) + _f26_s0_v0_forall], 1\1));
   @*/
   for (int _f26_s0_v1 = 0; _f26_s0_v1 < 0 + 3; _f26_s0_v1++)
   {
    int32_t _t1633 = (_f26_s0_v1 * 4);
    /*@
     loop_invariant 0 <= _f26_s0_v0 && _f26_s0_v0 <= 0 + 4;
     loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 4)) && ((0 <= _1) && (_1 < 3)); Perm(&_matrix_3200[(_1*4) + _0], 1\2));
     loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_3200[(_1*4) + _0] == pure_matrix_3200((_1*4) + _0));
     loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 4)) && ((0 <= _1) && (_1 < 3)); Perm(&_matrix_7000[(_1*4) + _0], 1\2));
     loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 4)) && (0 <= _1)) && (_1 < 3); _matrix_7000[(_1*4) + _0] == pure_matrix_7000((_1*4) + _0));
     loop_invariant (\forall* int _f26_s0_v0_forall; (0 <= _f26_s0_v0_forall) && (_f26_s0_v0_forall < 4); Perm(&_f26[(_f26_s0_v1*4) + _f26_s0_v0_forall], 1\1));
    @*/
    for (int _f26_s0_v0 = 0; _f26_s0_v0 < 0 + 4; _f26_s0_v0++)
    {
     int32_t _t1630 = (_f26_s0_v0 + _t1633);
     int16_t _10 = (int16_t)((((_matrix_3200[_t1630] * 0.248933) + (_matrix_7000[_t1630] * 0.751067)) * 256.000000));
     _f26[_t1630] = _10;
    } // for _f26_s0_v0
   } // for _f26_s0_v1
   {
    uint8_t _sharpen_strength_x32[1];
    // produce sharpen_strength_x32
    _sharpen_strength_x32[0] = 32;
    // produce processed
    // consume sharpen_strength_x32
    // consume f26
    // consume curve
    #pragma omp parallel for
    for (int _processed_s0_v1_v3_v4 = 0; _processed_s0_v1_v3_v4 < 0 + 60; _processed_s0_v1_v3_v4++)
    /*@
     context 0 <= _processed_s0_v1_v3_v4 && _processed_s0_v1_v3_v4 < 0 + 60;
     context (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
     context (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
     context (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
     context (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
     context Perm(&_sharpen_strength_x32[0], 1\(2*60));
     context (\forall* int _processed_s0_v2_forall, int _processed_s0_v0_forall, int _processed_s0_v1_v5_forall, int _processed_s0_v1_v3_v3_forall; (((((((0 <= _processed_s0_v1_v3_v3_forall) && (_processed_s0_v1_v3_v3_forall < 16)) && (0 <= _processed_s0_v1_v5_forall)) && (_processed_s0_v1_v5_forall < 2)) && (0 <= _processed_s0_v0_forall)) && (_processed_s0_v0_forall < 2560)) && (0 <= _processed_s0_v2_forall)) && (_processed_s0_v2_forall < 3); Perm(&_processed[(((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3_forall)*2) + _processed_s0_v1_v5_forall)*2560) + ((_processed_s0_v2_forall*4915200) + _processed_s0_v0_forall)], 1\1));
    @*/
    {
     {
      int64_t _11 = 102720;
      int16_t *_f3 = (int16_t  *)malloc(sizeof(int16_t )*_11);
      {
       int64_t _12 = 103280;
       int16_t *_deinterleaved = (int16_t  *)malloc(sizeof(int16_t )*_12);
       {
        int64_t _13 = 262752;
        uint8_t *_curved = (uint8_t  *)malloc(sizeof(uint8_t )*_13);
        int32_t _t1634 = (_processed_s0_v1_v3_v4 * 16);
        /*@
         loop_invariant 0 <= _processed_s0_v1_v3_v3 && _processed_s0_v1_v3_v3 <= 0 + 16;
         loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
         loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
         loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
         loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
         loop_invariant (\forall* int _v0, int _v1; (((-4 <= _v0) && (_v0 < 2564)) && (((_processed_s0_v1_v3_v4*32) + -4) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 36)); Perm(&_f3[(((_v1 - (_processed_s0_v1_v3_v4*32))*2568) + _v0) + 10276], 1\1));
         loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\1));
         loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-1 <= _v0) && (_v0 < 2575)) && (((_processed_s0_v1_v3_v4*32) + -1) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 33))) && (0 <= _v2)) && (_v2 < 3); Perm(&_curved[(((_v1 - (_processed_s0_v1_v3_v4*32))*2576) + ((_v2*87584) + _v0)) + 2577], 1\1));
         loop_invariant Perm(&_sharpen_strength_x32[0], 1\(2*60));
         loop_invariant (\forall* int _processed_s0_v2_forall, int _processed_s0_v0_forall, int _processed_s0_v1_v5_forall, int _processed_s0_v1_v3_v3_forall; (((((((0 <= _processed_s0_v1_v3_v3_forall) && (_processed_s0_v1_v3_v3_forall < 16)) && (0 <= _processed_s0_v1_v5_forall)) && (_processed_s0_v1_v5_forall < 2)) && (0 <= _processed_s0_v0_forall)) && (_processed_s0_v0_forall < 2560)) && (0 <= _processed_s0_v2_forall)) && (_processed_s0_v2_forall < 3); Perm(&_processed[(((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3_forall)*2) + _processed_s0_v1_v5_forall)*2560) + ((_processed_s0_v2_forall*4915200) + _processed_s0_v0_forall)], 1\1));
        @*/
        for (int _processed_s0_v1_v3_v3 = 0; _processed_s0_v1_v3_v3 < 0 + 16; _processed_s0_v1_v3_v3++)
        {
         // produce f3
         int32_t _t1635 = (_processed_s0_v1_v3_v3 + _t1634);
         /*@
          loop_invariant 0 <= _f3_s0_v1_v1 && _f3_s0_v1_v1 <= 0 + 5;
          loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
          loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
          loop_invariant (\forall* int _f3_s0_v0_v6_forall, int _f3_s0_v1_v3_forall, int _f3_s0_v0_v0_forall, int _f3_s0_v1_v1_forall; ((((((((0 <= _f3_s0_v1_v1_forall) && (_f3_s0_v1_v1_forall < 5)) && (0 <= _f3_s0_v0_v0_forall)) && (_f3_s0_v0_v0_forall < 161)) && (0 <= _f3_s0_v1_v3_forall)) && (_f3_s0_v1_v3_forall < 2)) && (0 <= _f3_s0_v0_v6_forall)) && (_f3_s0_v0_v6_forall < 16)) && (((_f3_s0_v0_v0_forall*16) + _f3_s0_v0_v6_forall) <= 2567); Perm(&_f3[((((_f3_s0_v1_v1_forall + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3_forall)*2568) + ((_f3_s0_v0_v0_forall*16) + _f3_s0_v0_v6_forall)], 1\1));
         @*/
         for (int _f3_s0_v1_v1 = 0; _f3_s0_v1_v1 < 0 + 5; _f3_s0_v1_v1++)
         {
          int32_t _t1636 = ((_f3_s0_v1_v1 + _t1635) * 2);
          int32_t _t1637 = ((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3) * 2);
          /*@
           loop_invariant 0 <= _f3_s0_v0_v0 && _f3_s0_v0_v0 <= 0 + 160;
           loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
           loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
           loop_invariant (\forall* int _f3_s0_v0_v6_forall, int _f3_s0_v1_v3_forall, int _f3_s0_v0_v0_forall; ((((((0 <= _f3_s0_v0_v0_forall) && (_f3_s0_v0_v0_forall < 161)) && (0 <= _f3_s0_v1_v3_forall)) && (_f3_s0_v1_v3_forall < 2)) && (0 <= _f3_s0_v0_v6_forall)) && (_f3_s0_v0_v6_forall < 16)) && (((_f3_s0_v0_v0_forall*16) + _f3_s0_v0_v6_forall) <= 2567); Perm(&_f3[((((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3_forall)*2568) + ((_f3_s0_v0_v0_forall*16) + _f3_s0_v0_v6_forall)], 1\1));
          @*/
          for (int _f3_s0_v0_v0 = 0; _f3_s0_v0_v0 < 0 + 160; _f3_s0_v0_v0++)
          {
           int32_t _t1638 = (_f3_s0_v0_v0 * 16);
           /*@
            loop_invariant 0 <= _f3_s0_v1_v3 && _f3_s0_v1_v3 <= 0 + 2;
            loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
            loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
            loop_invariant (\forall* int _f3_s0_v0_v6_forall, int _f3_s0_v1_v3_forall; (((0 <= _f3_s0_v1_v3_forall) && (_f3_s0_v1_v3_forall < 2)) && (0 <= _f3_s0_v0_v6_forall)) && (_f3_s0_v0_v6_forall < 16); Perm(&_f3[(_f3_s0_v0_v0*16) + (((((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3_forall)*2568) + _f3_s0_v0_v6_forall)], 1\1));
           @*/
           for (int _f3_s0_v1_v3 = 0; _f3_s0_v1_v3 < 0 + 2; _f3_s0_v1_v3++)
           {
            int32_t _t1640 = (((_f3_s0_v1_v3 + _t1637) * 2568) + _t1638);
            int32_t _t1639 = (((_f3_s0_v1_v3 + _t1636) * 2592) + _t1638);
            /*@
             loop_invariant 0 <= _f3_s0_v0_v6 && _f3_s0_v0_v6 <= 0 + 16;
             loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
             loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
             loop_invariant (\forall* int _f3_s0_v0_v6_forall; (0 <= _f3_s0_v0_v6_forall) && (_f3_s0_v0_v6_forall < 16); Perm(&_f3[((((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3)*2568) + ((_f3_s0_v0_v0*16) + _f3_s0_v0_v6_forall)], 1\1));
            @*/
            for (int _f3_s0_v0_v6 = 0; _f3_s0_v0_v6 < 0 + 16; _f3_s0_v0_v6++)
            {
             int32_t _t1571 = (_f3_s0_v0_v6 + _t1639);
             int16_t _14 = (int16_t)(_input[(_t1571 + 15564)]);
             int16_t _15 = (int16_t)(_input[(_t1571 + 25932)]);
             int16_t _16 = _14>_15 ? _14 : _15;
             int16_t _17 = (int16_t)(_input[(_t1571 + 20750)]);
             int16_t _18 = _16>_17 ? _16 : _17;
             int16_t _19 = (int16_t)(_input[(_t1571 + 20746)]);
             int16_t _20 = _18>_19 ? _18 : _19;
             int16_t _21 = (int16_t)(_input[(_t1571 + 20748)]);
             int16_t _22 = _20<_21 ? _20 : _21;
             int16_t _23 = _22>0 ? _22 : 0;
             _f3[(_f3_s0_v0_v6 + _t1640)] = _23;
            } // for _f3_s0_v0_v6
           } // for _f3_s0_v1_v3
          } // for _f3_s0_v0_v0
          int32_t _t1641 = ((_f3_s0_v1_v1 + _t1635) * 2);
          int32_t _t1642 = ((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3) * 2);
          /*@
           loop_invariant 0 <= _f3_s0_v1_v3 && _f3_s0_v1_v3 <= 0 + 2;
           loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
           loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
           loop_invariant (\forall* int _f3_s0_v0_v6_forall, int _f3_s0_v1_v3_forall; ((((0 <= _f3_s0_v1_v3_forall) && (_f3_s0_v1_v3_forall < 2)) && (0 <= _f3_s0_v0_v6_forall)) && (_f3_s0_v0_v6_forall < 16)) && (_f3_s0_v0_v6_forall <= 7); Perm(&_f3[(((((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3_forall)*2568) + _f3_s0_v0_v6_forall) + 2560], 1\1));
          @*/
          for (int _f3_s0_v1_v3 = 0; _f3_s0_v1_v3 < 0 + 2; _f3_s0_v1_v3++)
          {
           int32_t _t1644 = ((_f3_s0_v1_v3 + _t1642) * 2568);
           int32_t _t1643 = ((_f3_s0_v1_v3 + _t1641) * 2592);
           /*@
            loop_invariant 0 <= _f3_s0_v0_v6 && _f3_s0_v0_v6 <= 0 + 8;
            loop_invariant (\forall* int _0, int _1; ((0 <= _0) && (_0 < 2592)) && ((0 <= _1) && (_1 < 1968)); Perm(&_input[(_1*2592) + _0], 1\(2*60)));
            loop_invariant (\forall int _0, int _1; (((0 <= _0) && (_0 < 2592)) && (0 <= _1)) && (_1 < 1968); _input[(_1*2592) + _0] == pure_input((_1*2592) + _0));
            loop_invariant (\forall* int _f3_s0_v0_v6_forall; ((0 <= _f3_s0_v0_v6_forall) && (_f3_s0_v0_v6_forall < 16)) && (_f3_s0_v0_v6_forall <= 7); Perm(&_f3[(((((_f3_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _f3_s0_v1_v3)*2568) + _f3_s0_v0_v6_forall) + 2560], 1\1));
           @*/
           for (int _f3_s0_v0_v6 = 0; _f3_s0_v0_v6 < 0 + 8; _f3_s0_v0_v6++)
           {
            int32_t _t1631 = (_f3_s0_v0_v6 + _t1643);
            int16_t _24 = (int16_t)(_input[(_t1631 + 18124)]);
            int16_t _25 = (int16_t)(_input[(_t1631 + 28492)]);
            int16_t _26 = _24>_25 ? _24 : _25;
            int16_t _27 = (int16_t)(_input[(_t1631 + 23310)]);
            int16_t _28 = _26>_27 ? _26 : _27;
            int16_t _29 = (int16_t)(_input[(_t1631 + 23306)]);
            int16_t _30 = _28>_29 ? _28 : _29;
            int16_t _31 = (int16_t)(_input[(_t1631 + 23308)]);
            int16_t _32 = _30<_31 ? _30 : _31;
            int16_t _33 = _32>0 ? _32 : 0;
            _f3[((_f3_s0_v0_v6 + _t1644) + 2560)] = _33;
           } // for _f3_s0_v0_v6
          } // for _f3_s0_v1_v3
         } // for _f3_s0_v1_v1
         // produce deinterleaved
         // consume f3
         int32_t _t1645 = (_processed_s0_v1_v3_v3 + _t1634);
         /*@
          loop_invariant (_t1645 + -2) <= _deinterleaved_s0_v1 && _deinterleaved_s0_v1 <= (_t1645 + -2) + 5;
          loop_invariant (\forall* int _v0, int _v1; (((-4 <= _v0) && (_v0 < 2564)) && (((_processed_s0_v1_v3_v4*32) + -4) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 36)); Perm(&_f3[(((_v1 - (_processed_s0_v1_v3_v4*32))*2568) + _v0) + 10276], 1\2));
          loop_invariant (\forall* int _deinterleaved_s0_v2_forall, int _deinterleaved_s0_v0_forall, int _deinterleaved_s0_v1_forall; ((((((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + -2) <= _deinterleaved_s0_v1_forall) && (_deinterleaved_s0_v1_forall < (((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + 3))) && (-2 <= _deinterleaved_s0_v0_forall)) && (_deinterleaved_s0_v0_forall < 1282)) && (0 <= _deinterleaved_s0_v2_forall)) && (_deinterleaved_s0_v2_forall < 4); Perm(&_deinterleaved[(((_deinterleaved_s0_v1_forall - (_processed_s0_v1_v3_v4*16))*1291) + ((_deinterleaved_s0_v2_forall*25820) + _deinterleaved_s0_v0_forall)) + 2584], 1\1));
         @*/
         for (int _deinterleaved_s0_v1 = (_t1645 + -2); _deinterleaved_s0_v1 < (_t1645 + -2) + 5; _deinterleaved_s0_v1++)
         {
          int32_t _t1646 = (_deinterleaved_s0_v1 - _t1634);
          /*@
           loop_invariant -2 <= _deinterleaved_s0_v0 && _deinterleaved_s0_v0 <= -2 + 1284;
           loop_invariant (\forall* int _v0, int _v1; (((-4 <= _v0) && (_v0 < 2564)) && (((_processed_s0_v1_v3_v4*32) + -4) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 36)); Perm(&_f3[(((_v1 - (_processed_s0_v1_v3_v4*32))*2568) + _v0) + 10276], 1\2));
           loop_invariant (\forall* int _deinterleaved_s0_v2_forall, int _deinterleaved_s0_v0_forall; (((-2 <= _deinterleaved_s0_v0_forall) && (_deinterleaved_s0_v0_forall < 1282)) && (0 <= _deinterleaved_s0_v2_forall)) && (_deinterleaved_s0_v2_forall < 4); Perm(&_deinterleaved[(((_deinterleaved_s0_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_deinterleaved_s0_v2_forall*25820) + _deinterleaved_s0_v0_forall)) + 2584], 1\1));
          @*/
          for (int _deinterleaved_s0_v0 = -2; _deinterleaved_s0_v0 < -2 + 1284; _deinterleaved_s0_v0++)
          {
           int32_t _t1647 = ((_t1646 * 2568) + _deinterleaved_s0_v0);
           int32_t _t1648 = ((_t1646 * 1291) + _deinterleaved_s0_v0);
           /*@
            loop_invariant 0 <= _deinterleaved_s0_v2 && _deinterleaved_s0_v2 <= 0 + 4;
            loop_invariant (\forall* int _v0, int _v1; (((-4 <= _v0) && (_v0 < 2564)) && (((_processed_s0_v1_v3_v4*32) + -4) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 36)); Perm(&_f3[(((_v1 - (_processed_s0_v1_v3_v4*32))*2568) + _v0) + 10276], 1\2));
            loop_invariant (\forall* int _deinterleaved_s0_v2_forall; (0 <= _deinterleaved_s0_v2_forall) && (_deinterleaved_s0_v2_forall < 4); Perm(&_deinterleaved[((((_deinterleaved_s0_v2_forall*20) + (_deinterleaved_s0_v1 - (_processed_s0_v1_v3_v4*16)))*1291) + _deinterleaved_s0_v0) + 2584], 1\1));
           @*/
           for (int _deinterleaved_s0_v2 = 0; _deinterleaved_s0_v2 < 0 + 4; _deinterleaved_s0_v2++)
           {
            _deinterleaved[(((_deinterleaved_s0_v2 * 25820) + _t1648) + 2584)] = ((_deinterleaved_s0_v2 == 0) ? _f3[((_t1647 * 2) + 10276)] : ((_deinterleaved_s0_v2 == 1) ? _f3[((_t1647 * 2) + 10277)] : ((_deinterleaved_s0_v2 == 2) ? _f3[((_t1647 * 2) + 12844)] : ((_deinterleaved_s0_v2 == 3) ? _f3[((_t1647 * 2) + 12845)] : _f3[((_t1647 * 2) + 12845)]))));
           } // for _deinterleaved_s0_v2
          } // for _deinterleaved_s0_v0
         } // for _deinterleaved_s0_v1
         // produce curved
         // consume deinterleaved
         /*@
          loop_invariant 0 <= _curved_s0_v1_v1 && _curved_s0_v1_v1 <= 0 + 2;
          loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
          loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
          loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\2));
          loop_invariant (\forall* int _curved_s0_v2_forall, int _curved_s0_v0_v6_forall, int _curved_s0_v1_v3_forall, int _curved_s0_v0_v0_forall, int _curved_s0_v1_v1_forall; (((((((((0 <= _curved_s0_v1_v1_forall) && (_curved_s0_v1_v1_forall < 2)) && (0 <= _curved_s0_v0_v0_forall)) && (_curved_s0_v0_v0_forall < 161)) && (0 <= _curved_s0_v1_v3_forall)) && (_curved_s0_v1_v3_forall < 2)) && (0 <= _curved_s0_v0_v6_forall)) && (_curved_s0_v0_v6_forall < 16)) && (0 <= _curved_s0_v2_forall)) && (_curved_s0_v2_forall < 3); Perm(&_curved[((((_curved_s0_v1_v1_forall + _processed_s0_v1_v3_v3)*2) + _curved_s0_v1_v3_forall)*2576) + ((((_curved_s0_v2_forall*5474) + _curved_s0_v0_v0_forall)*16) + _curved_s0_v0_v6_forall)], 1\1));
         @*/
         for (int _curved_s0_v1_v1 = 0; _curved_s0_v1_v1 < 0 + 2; _curved_s0_v1_v1++)
         {
          int32_t _t1650 = (((_processed_s0_v1_v3_v3 + _t1634) + _curved_s0_v1_v1) * 2);
          int32_t _t1651 = ((_curved_s0_v1_v1 + _processed_s0_v1_v3_v3) * 2);
          /*@
           loop_invariant 0 <= _curved_s0_v0_v0 && _curved_s0_v0_v0 <= 0 + 161;
           loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
           loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
           loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\2));
           loop_invariant (\forall* int _curved_s0_v2_forall, int _curved_s0_v0_v6_forall, int _curved_s0_v1_v3_forall, int _curved_s0_v0_v0_forall; (((((((0 <= _curved_s0_v0_v0_forall) && (_curved_s0_v0_v0_forall < 161)) && (0 <= _curved_s0_v1_v3_forall)) && (_curved_s0_v1_v3_forall < 2)) && (0 <= _curved_s0_v0_v6_forall)) && (_curved_s0_v0_v6_forall < 16)) && (0 <= _curved_s0_v2_forall)) && (_curved_s0_v2_forall < 3); Perm(&_curved[((((_curved_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _curved_s0_v1_v3_forall)*2576) + ((((_curved_s0_v2_forall*5474) + _curved_s0_v0_v0_forall)*16) + _curved_s0_v0_v6_forall)], 1\1));
          @*/
          for (int _curved_s0_v0_v0 = 0; _curved_s0_v0_v0 < 0 + 161; _curved_s0_v0_v0++)
          {
           {
            int16_t _f27[96];
            // produce f27
            int32_t _t1652 = (_curved_s0_v0_v0 * 16);
            /*@
             loop_invariant (_t1650 + -1) <= _f27_s0_v1 && _f27_s0_v1 <= (_t1650 + -1) + 2;
             loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
             loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\2));
             loop_invariant (\forall* int _f27_s0_v2_forall, int _f27_s0_v0_forall, int _f27_s0_v1_forall; ((((((((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + -1) <= _f27_s0_v1_forall) && (_f27_s0_v1_forall < (((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + 1))) && (((_curved_s0_v0_v0*16) + -1) <= _f27_s0_v0_forall)) && (_f27_s0_v0_forall < ((_curved_s0_v0_v0*16) + 15))) && (0 <= _f27_s0_v2_forall)) && (_f27_s0_v2_forall < 3); Perm(&_f27[((((_f27_s0_v1_forall - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2))*16) + ((_f27_s0_v2_forall*32) + _f27_s0_v0_forall)) - (_curved_s0_v0_v0*16)) + 17], 1\1));
            @*/
            for (int _f27_s0_v1 = (_t1650 + -1); _f27_s0_v1 < (_t1650 + -1) + 2; _f27_s0_v1++)
            {
             bool _t1653 = (mod_eucl(_f27_s0_v1, 2) == 0);
             int32_t _t1654 = ((div_eucl(_f27_s0_v1, 2) - _t1634) * 1291);
             int32_t _t1655 = (((_f27_s0_v1 - _t1650) * 16) - _t1652);
             /*@
              loop_invariant (_t1652 + -1) <= _f27_s0_v0 && _f27_s0_v0 <= (_t1652 + -1) + 16;
              loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
              loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\2));
              loop_invariant (\forall* int _f27_s0_v2_forall, int _f27_s0_v0_forall; (((((_curved_s0_v0_v0*16) + -1) <= _f27_s0_v0_forall) && (_f27_s0_v0_forall < ((_curved_s0_v0_v0*16) + 15))) && (0 <= _f27_s0_v2_forall)) && (_f27_s0_v2_forall < 3); Perm(&_f27[(((_f27_s0_v1 - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2))*16) + (((_f27_s0_v2_forall*32) + _f27_s0_v0_forall) - (_curved_s0_v0_v0*16))) + 17], 1\1));
             @*/
             for (int _f27_s0_v0 = (_t1652 + -1); _f27_s0_v0 < (_t1652 + -1) + 16; _f27_s0_v0++)
             {
              bool _t1656 = (mod_eucl(_f27_s0_v0, 2) == 0);
              int32_t _t1657 = (div_eucl(_f27_s0_v0, 2) + _t1654);
              int32_t _t1658 = (_f27_s0_v0 + _t1655);
              /*@
               loop_invariant 0 <= _f27_s0_v2 && _f27_s0_v2 <= 0 + 3;
               loop_invariant (\forall* int _v0, int _v1; (((0 <= _v0) && (_v0 < 4)) && (0 <= _v1)) && (_v1 < 3); Perm(&_f26[(_v1*4) + _v0], 1\(2*60)));
               loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-2 <= _v0) && (_v0 < 1289)) && (((_processed_s0_v1_v3_v4*16) + -2) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*16) + 18))) && (0 <= _v2)) && (_v2 < 4); Perm(&_deinterleaved[(((_v1 - (_processed_s0_v1_v3_v4*16))*1291) + ((_v2*25820) + _v0)) + 2584], 1\2));
               loop_invariant (\forall* int _f27_s0_v2_forall; (0 <= _f27_s0_v2_forall) && (_f27_s0_v2_forall < 3); Perm(&_f27[(((((_f27_s0_v2_forall*2) - _curved_s0_v0_v0) + (_f27_s0_v1 - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2)))*16) + _f27_s0_v0) + 17], 1\1));
              @*/
              for (int _f27_s0_v2 = 0; _f27_s0_v2 < 0 + 3; _f27_s0_v2++)
              {
               int16_t _t1578 = _deinterleaved[(_t1657 + 2584)];
               int16_t _t1579 = _deinterleaved[(_t1657 + 80043)];
               int16_t _t1580 = _deinterleaved[(_t1657 + 80044)];
               int16_t _t1581 = _deinterleaved[(_t1657 + 3875)];
               int32_t _34 = (int32_t)(_t1579);
               int32_t _35 = (int32_t)(_t1580);
               int16_t _36 = (int16_t)(div_eucl(((_34 + _35) + 1), 2));
               int32_t _37 = (int32_t)(_t1581);
               int32_t _38 = (int32_t)(_t1578);
               int16_t _39 = (int16_t)(div_eucl(((_37 + _38) + 1), 2));
               uint16_t _40 = (uint16_t)(((_t1579 < _t1580) ? (_t1580 - _t1579) : (_t1579 - _t1580)));
               uint16_t _41 = (uint16_t)(((_t1581 < _t1578) ? (_t1578 - _t1581) : (_t1581 - _t1578)));
               int16_t _t1586 = ((_40 < _41) ? _36 : _39);
               int16_t _t1588 = _deinterleaved[(_t1657 + 78752)];
               int16_t _t1589 = _deinterleaved[(_t1657 + 78753)];
               int16_t _t1590 = _deinterleaved[(_t1657 + 1293)];
               int32_t _42 = (int32_t)(_t1588);
               int32_t _43 = (int32_t)(_t1589);
               int16_t _44 = (int16_t)(div_eucl(((_42 + _43) + 1), 2));
               int32_t _45 = (int32_t)(_t1590);
               int16_t _46 = (int16_t)(div_eucl(((_38 + _45) + 1), 2));
               uint16_t _47 = (uint16_t)(((_t1588 < _t1589) ? (_t1589 - _t1588) : (_t1588 - _t1589)));
               uint16_t _48 = (uint16_t)(((_t1578 < _t1590) ? (_t1590 - _t1578) : (_t1578 - _t1590)));
               int16_t _t1593_s = ((_47 < _48) ? _44 : _46);
               int16_t _t1594 = _deinterleaved[(_t1657 + 54224)];
               int16_t _t1596 = _deinterleaved[(_t1657 + 52933)];
               int16_t _t1598 = _deinterleaved[(_t1657 + 52934)];
               int16_t _t1599 = _deinterleaved[(_t1657 + 54225)];
               int16_t _t1600 = _deinterleaved[(_t1657 + 2585)];
               int32_t _49 = (int32_t)(_t1600);
               int16_t _50 = (int16_t)(div_eucl(((_49 + _38) + 1), 2));
               int16_t _51 = (int16_t)(div_eucl(((_43 + _35) + 1), 2));
               uint16_t _52 = (uint16_t)(((_t1600 < _t1578) ? (_t1578 - _t1600) : (_t1600 - _t1578)));
               uint16_t _53 = (uint16_t)(((_t1589 < _t1580) ? (_t1580 - _t1589) : (_t1589 - _t1580)));
               int16_t _t1602 = ((_52 < _53) ? _50 : _51);
               int16_t _t1603 = _deinterleaved[(_t1657 + 78754)];
               int16_t _t1604 = _deinterleaved[(_t1657 + 1294)];
               int16_t _t1605 = _deinterleaved[(_t1657 + 80045)];
               int16_t _t1606 = _deinterleaved[(_t1657 + 3876)];
               int32_t _54 = (int32_t)(_t1605);
               int16_t _55 = (int16_t)(div_eucl(((_35 + _54) + 1), 2));
               int32_t _56 = (int32_t)(_t1606);
               int16_t _57 = (int16_t)(div_eucl(((_56 + _49) + 1), 2));
               uint16_t _58 = (uint16_t)(((_t1580 < _t1605) ? (_t1605 - _t1580) : (_t1580 - _t1605)));
               uint16_t _59 = (uint16_t)(((_t1606 < _t1600) ? (_t1600 - _t1606) : (_t1606 - _t1600)));
               int16_t _t1608_s = ((_58 < _59) ? _55 : _57);
               int32_t _60 = (int32_t)(_t1586);
               int32_t _61 = (int32_t)(_t1593_s);
               int16_t _62 = (int16_t)(div_eucl(((_60 + _61) + 1), 2));
               int32_t _63 = (int32_t)(_t1594);
               int32_t _64 = (int32_t)(_t1596);
               int16_t _65 = (int16_t)(div_eucl(((_63 + _64) + 1), 2));
               int32_t _66 = (int32_t)(_t1603);
               int16_t _67 = (int16_t)(div_eucl(((_43 + _66) + 1), 2));
               int32_t _68 = (int32_t)(_t1604);
               int16_t _69 = (int16_t)(div_eucl(((_49 + _68) + 1), 2));
               uint16_t _70 = (uint16_t)(((_t1589 < _t1603) ? (_t1603 - _t1589) : (_t1589 - _t1603)));
               uint16_t _71 = (uint16_t)(((_t1600 < _t1604) ? (_t1604 - _t1600) : (_t1600 - _t1604)));
               int32_t _72 = (int32_t)(((_70 < _71) ? _67 : _69));
               int16_t _73 = (int16_t)(div_eucl(((_60 + _72) + 1), 2));
               int32_t _74 = (int32_t)(_t1598);
               int16_t _75 = (int16_t)(div_eucl(((_63 + _74) + 1), 2));
               int32_t _76 = (int32_t)(_t1608_s);
               int16_t _77 = (int16_t)(div_eucl(((_76 + _61) + 1), 2));
               int32_t _78 = (int32_t)(_t1599);
               int16_t _79 = (int16_t)(div_eucl(((_78 + _64) + 1), 2));
               uint16_t _80 = (uint16_t)(((_t1594 < _t1598) ? (_t1598 - _t1594) : (_t1594 - _t1598)));
               uint16_t _81 = (uint16_t)(((_t1599 < _t1596) ? (_t1596 - _t1599) : (_t1599 - _t1596)));
               int16_t _82 = (int16_t)(div_eucl(((_60 + _76) + 1), 2));
               int16_t _83 = (int16_t)(div_eucl(((_63 + _78) + 1), 2));
               int16_t _t1610_s = (_t1653 ? (_t1656 ? ((_t1578 - _62) + _65) : ((_80 < _81) ? ((_t1602 - _73) + _75) : ((_t1602 - _77) + _79))) : (_t1656 ? _t1594 : ((_t1580 - _82) + _83)));
               int16_t _t1611_s = (_t1653 ? (_t1656 ? _t1578 : _t1602) : (_t1656 ? _t1586 : _t1580));
               int16_t _t1613 = _deinterleaved[(_t1657 + 2583)];
               int32_t _84 = (int32_t)(_t1613);
               int16_t _85 = (int16_t)(div_eucl(((_38 + _84) + 1), 2));
               int16_t _86 = (int16_t)(div_eucl(((_42 + _34) + 1), 2));
               uint16_t _87 = (uint16_t)(((_t1578 < _t1613) ? (_t1613 - _t1578) : (_t1578 - _t1613)));
               uint16_t _88 = (uint16_t)(((_t1588 < _t1579) ? (_t1579 - _t1588) : (_t1588 - _t1579)));
               int16_t _t1614_s = ((_87 < _88) ? _85 : _86);
               int16_t _t1615 = _deinterleaved[(_t1657 + 28403)];
               int16_t _t1617 = _deinterleaved[(_t1657 + 28404)];
               int16_t _t1619 = _deinterleaved[(_t1657 + 29694)];
               int16_t _t1620 = _deinterleaved[(_t1657 + 29695)];
               int16_t _t1621 = _deinterleaved[(_t1657 + 3874)];
               int16_t _t1622 = _deinterleaved[(_t1657 + 81334)];
               int16_t _t1623 = _deinterleaved[(_t1657 + 81335)];
               int16_t _89 = (int16_t)(div_eucl(((_56 + _37) + 1), 2));
               int32_t _90 = (int32_t)(_t1623);
               int16_t _91 = (int16_t)(div_eucl(((_35 + _90) + 1), 2));
               uint16_t _92 = (uint16_t)(((_t1606 < _t1581) ? (_t1581 - _t1606) : (_t1606 - _t1581)));
               uint16_t _93 = (uint16_t)(((_t1580 < _t1623) ? (_t1623 - _t1580) : (_t1580 - _t1623)));
               int16_t _t1624_s = ((_92 < _93) ? _89 : _91);
               int32_t _94 = (int32_t)(_t1602);
               int32_t _95 = (int32_t)(_t1614_s);
               int16_t _96 = (int16_t)(div_eucl(((_94 + _95) + 1), 2));
               int32_t _97 = (int32_t)(_t1615);
               int32_t _98 = (int32_t)(_t1617);
               int16_t _99 = (int16_t)(div_eucl(((_97 + _98) + 1), 2));
               int32_t _100 = (int32_t)(_t1621);
               int16_t _101 = (int16_t)(div_eucl(((_37 + _100) + 1), 2));
               int32_t _102 = (int32_t)(_t1622);
               int16_t _103 = (int16_t)(div_eucl(((_34 + _102) + 1), 2));
               uint16_t _104 = (uint16_t)(((_t1581 < _t1621) ? (_t1621 - _t1581) : (_t1581 - _t1621)));
               uint16_t _105 = (uint16_t)(((_t1579 < _t1622) ? (_t1622 - _t1579) : (_t1579 - _t1622)));
               int32_t _106 = (int32_t)(((_104 < _105) ? _101 : _103));
               int16_t _107 = (int16_t)(div_eucl(((_94 + _106) + 1), 2));
               int32_t _108 = (int32_t)(_t1619);
               int16_t _109 = (int16_t)(div_eucl(((_98 + _108) + 1), 2));
               int32_t _110 = (int32_t)(_t1624_s);
               int16_t _111 = (int16_t)(div_eucl(((_95 + _110) + 1), 2));
               int32_t _112 = (int32_t)(_t1620);
               int16_t _113 = (int16_t)(div_eucl(((_97 + _112) + 1), 2));
               uint16_t _114 = (uint16_t)(((_t1617 < _t1619) ? (_t1619 - _t1617) : (_t1617 - _t1619)));
               uint16_t _115 = (uint16_t)(((_t1615 < _t1620) ? (_t1620 - _t1615) : (_t1615 - _t1620)));
               int16_t _116 = (int16_t)(div_eucl(((_94 + _110) + 1), 2));
               int16_t _117 = (int16_t)(div_eucl(((_98 + _112) + 1), 2));
               int16_t _t1626_s = (_t1653 ? (_t1656 ? ((_t1578 - _96) + _99) : _t1617) : (_t1656 ? ((_114 < _115) ? ((_t1586 - _107) + _109) : ((_t1586 - _111) + _113)) : ((_t1580 - _116) + _117)));
               int32_t _118 = (int32_t)(_f26[0]);
               int32_t _119 = (int32_t)(_t1626_s);
               int32_t _120 = (int32_t)(_f26[1]);
               int32_t _121 = (int32_t)(_t1611_s);
               int32_t _122 = (int32_t)(_f26[2]);
               int32_t _123 = (int32_t)(_t1610_s);
               int32_t _124 = (int32_t)(_f26[3]);
               int16_t _125 = (int16_t)(div_eucl(((_118 * _119) + ((_120 * _121) + ((_122 * _123) + _124))), 256));
               int32_t _126 = (int32_t)(_f26[4]);
               int32_t _127 = (int32_t)(_f26[5]);
               int32_t _128 = (int32_t)(_f26[6]);
               int32_t _129 = (int32_t)(_f26[7]);
               int16_t _130 = (int16_t)(div_eucl(((_126 * _119) + ((_127 * _121) + ((_128 * _123) + _129))), 256));
               int32_t _131 = (int32_t)(_f26[8]);
               int32_t _132 = (int32_t)(_f26[9]);
               int32_t _133 = (int32_t)(_f26[10]);
               int32_t _134 = (int32_t)(_f26[11]);
               int16_t _135 = (int16_t)(div_eucl(((_131 * _119) + ((_132 * _121) + ((_133 * _123) + _134))), 256));
               _f27[(((_f27_s0_v2 * 32) + _t1658) + 17)] = ((_f27_s0_v2 == 0) ? _125 : ((_f27_s0_v2 == 1) ? _130 : ((_f27_s0_v2 == 2) ? _135 : _135)));
              } // for _f27_s0_v2
             } // for _f27_s0_v0
            } // for _f27_s0_v1
            // consume f27
            int32_t _t1659 = (_curved_s0_v0_v0 * 16);
            /*@
             loop_invariant 0 <= _curved_s0_v1_v3 && _curved_s0_v1_v3 <= 0 + 2;
             loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
             loop_invariant (\forall* int _v0, int _v1, int _v2; (((((((_curved_s0_v0_v0*16) + -1) <= _v0) && (_v0 < ((_curved_s0_v0_v0*16) + 15))) && ((((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + -1) <= _v1)) && (_v1 < (((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + 1))) && (0 <= _v2)) && (_v2 < 3); Perm(&_f27[((((_v1 - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2))*16) + ((_v2*32) + _v0)) - (_curved_s0_v0_v0*16)) + 17], 1\2));
             loop_invariant (\forall* int _curved_s0_v2_forall, int _curved_s0_v0_v6_forall, int _curved_s0_v1_v3_forall; (((((0 <= _curved_s0_v1_v3_forall) && (_curved_s0_v1_v3_forall < 2)) && (0 <= _curved_s0_v0_v6_forall)) && (_curved_s0_v0_v6_forall < 16)) && (0 <= _curved_s0_v2_forall)) && (_curved_s0_v2_forall < 3); Perm(&_curved[(_curved_s0_v0_v0*16) + (((((_curved_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _curved_s0_v1_v3_forall)*2576) + ((_curved_s0_v2_forall*87584) + _curved_s0_v0_v6_forall))], 1\1));
            @*/
            for (int _curved_s0_v1_v3 = 0; _curved_s0_v1_v3 < 0 + 2; _curved_s0_v1_v3++)
            {
             int32_t _t1660 = (_curved_s0_v1_v3 * 16);
             int32_t _t1661 = (((_curved_s0_v1_v3 + _t1651) * 2576) + _t1659);
             /*@
              loop_invariant 0 <= _curved_s0_v0_v6 && _curved_s0_v0_v6 <= 0 + 16;
              loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
              loop_invariant (\forall* int _v0, int _v1, int _v2; (((((((_curved_s0_v0_v0*16) + -1) <= _v0) && (_v0 < ((_curved_s0_v0_v0*16) + 15))) && ((((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + -1) <= _v1)) && (_v1 < (((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + 1))) && (0 <= _v2)) && (_v2 < 3); Perm(&_f27[((((_v1 - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2))*16) + ((_v2*32) + _v0)) - (_curved_s0_v0_v0*16)) + 17], 1\2));
              loop_invariant (\forall* int _curved_s0_v2_forall, int _curved_s0_v0_v6_forall; (((0 <= _curved_s0_v0_v6_forall) && (_curved_s0_v0_v6_forall < 16)) && (0 <= _curved_s0_v2_forall)) && (_curved_s0_v2_forall < 3); Perm(&_curved[((((_curved_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _curved_s0_v1_v3)*2576) + ((_curved_s0_v0_v0*16) + ((_curved_s0_v2_forall*87584) + _curved_s0_v0_v6_forall))], 1\1));
             @*/
             for (int _curved_s0_v0_v6 = 0; _curved_s0_v0_v6 < 0 + 16; _curved_s0_v0_v6++)
             {
              int32_t _t1663 = (_curved_s0_v0_v6 + _t1661);
              int32_t _t1662 = (_curved_s0_v0_v6 + _t1660);
              /*@
               loop_invariant 0 <= _curved_s0_v2 && _curved_s0_v2 <= 0 + 3;
               loop_invariant (\forall* int _v0; (0 <= _v0) && (_v0 < 1024); Perm(&_curve[_v0], 1\(2*60)));
               loop_invariant (\forall* int _v0, int _v1, int _v2; (((((((_curved_s0_v0_v0*16) + -1) <= _v0) && (_v0 < ((_curved_s0_v0_v0*16) + 15))) && ((((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + -1) <= _v1)) && (_v1 < (((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2) + 1))) && (0 <= _v2)) && (_v2 < 3); Perm(&_f27[((((_v1 - ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3) + _curved_s0_v1_v1)*2))*16) + ((_v2*32) + _v0)) - (_curved_s0_v0_v0*16)) + 17], 1\2));
               loop_invariant (\forall* int _curved_s0_v2_forall; (0 <= _curved_s0_v2_forall) && (_curved_s0_v2_forall < 3); Perm(&_curved[((((((_curved_s0_v1_v1 + _processed_s0_v1_v3_v3)*2) + _curved_s0_v1_v3)*161) + ((_curved_s0_v2_forall*5474) + _curved_s0_v0_v0))*16) + _curved_s0_v0_v6], 1\1));
              @*/
              for (int _curved_s0_v2 = 0; _curved_s0_v2 < 0 + 3; _curved_s0_v2++)
              {
               int16_t _136 = _f27[((_curved_s0_v2 * 32) + _t1662)]<1023 ? _f27[((_curved_s0_v2 * 32) + _t1662)] : 1023;
               int16_t _137 = _136>0 ? _136 : 0;
               int32_t _138 = (int32_t)(_137);
               _curved[((_curved_s0_v2 * 87584) + _t1663)] = _curve[_138];
              } // for _curved_s0_v2
             } // for _curved_s0_v0_v6
            } // for _curved_s0_v1_v3
           } // alloc _f27
          } // for _curved_s0_v0_v0
         } // for _curved_s0_v1_v1
         // consume curved
         int32_t _t1665 = ((_processed_s0_v1_v3_v3 + _t1634) * 2);
         int32_t _t1664 = (_processed_s0_v1_v3_v3 * 2);
         /*@
          loop_invariant 0 <= _processed_s0_v1_v5 && _processed_s0_v1_v5 <= 0 + 2;
          loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-1 <= _v0) && (_v0 < 2575)) && (((_processed_s0_v1_v3_v4*32) + -1) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 33))) && (0 <= _v2)) && (_v2 < 3); Perm(&_curved[(((_v1 - (_processed_s0_v1_v3_v4*32))*2576) + ((_v2*87584) + _v0)) + 2577], 1\2));
          loop_invariant Perm(&_sharpen_strength_x32[0], 1\(2*60));
          loop_invariant (\forall* int _processed_s0_v2_forall, int _processed_s0_v0_forall, int _processed_s0_v1_v5_forall; (((((0 <= _processed_s0_v1_v5_forall) && (_processed_s0_v1_v5_forall < 2)) && (0 <= _processed_s0_v0_forall)) && (_processed_s0_v0_forall < 2560)) && (0 <= _processed_s0_v2_forall)) && (_processed_s0_v2_forall < 3); Perm(&_processed[(((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3)*2) + _processed_s0_v1_v5_forall)*2560) + ((_processed_s0_v2_forall*4915200) + _processed_s0_v0_forall)], 1\1));
         @*/
         for (int _processed_s0_v1_v5 = 0; _processed_s0_v1_v5 < 0 + 2; _processed_s0_v1_v5++)
         {
          int32_t _t1667 = ((_processed_s0_v1_v5 + _t1665) * 2560);
          int32_t _t1666 = ((_processed_s0_v1_v5 + _t1664) * 2576);
          /*@
           loop_invariant 0 <= _processed_s0_v0 && _processed_s0_v0 <= 0 + 2560;
           loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-1 <= _v0) && (_v0 < 2575)) && (((_processed_s0_v1_v3_v4*32) + -1) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 33))) && (0 <= _v2)) && (_v2 < 3); Perm(&_curved[(((_v1 - (_processed_s0_v1_v3_v4*32))*2576) + ((_v2*87584) + _v0)) + 2577], 1\2));
           loop_invariant Perm(&_sharpen_strength_x32[0], 1\(2*60));
           loop_invariant (\forall* int _processed_s0_v2_forall, int _processed_s0_v0_forall; (((0 <= _processed_s0_v0_forall) && (_processed_s0_v0_forall < 2560)) && (0 <= _processed_s0_v2_forall)) && (_processed_s0_v2_forall < 3); Perm(&_processed[(((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3)*2) + _processed_s0_v1_v5)*2560) + ((_processed_s0_v2_forall*4915200) + _processed_s0_v0_forall)], 1\1));
          @*/
          for (int _processed_s0_v0 = 0; _processed_s0_v0 < 0 + 2560; _processed_s0_v0++)
          {
           int32_t _t1669 = (_processed_s0_v0 + _t1667);
           int32_t _t1668 = (_processed_s0_v0 + _t1666);
           /*@
            loop_invariant 0 <= _processed_s0_v2 && _processed_s0_v2 <= 0 + 3;
            loop_invariant (\forall* int _v0, int _v1, int _v2; (((((-1 <= _v0) && (_v0 < 2575)) && (((_processed_s0_v1_v3_v4*32) + -1) <= _v1)) && (_v1 < ((_processed_s0_v1_v3_v4*32) + 33))) && (0 <= _v2)) && (_v2 < 3); Perm(&_curved[(((_v1 - (_processed_s0_v1_v3_v4*32))*2576) + ((_v2*87584) + _v0)) + 2577], 1\2));
            loop_invariant Perm(&_sharpen_strength_x32[0], 1\(2*60));
            loop_invariant (\forall* int _processed_s0_v2_forall; (0 <= _processed_s0_v2_forall) && (_processed_s0_v2_forall < 3); Perm(&_processed[(((_processed_s0_v2_forall*1920) + ((((_processed_s0_v1_v3_v4*16) + _processed_s0_v1_v3_v3)*2) + _processed_s0_v1_v5))*2560) + _processed_s0_v0], 1\1));
           @*/
           for (int _processed_s0_v2 = 0; _processed_s0_v2 < 0 + 3; _processed_s0_v2++)
           {
            int32_t _t1627 = ((_processed_s0_v2 * 87584) + _t1668);
            uint8_t _t1628 = _curved[(_t1627 + 2577)];
            int16_t _139 = (int16_t)(_t1628);
            uint16_t _140 = (uint16_t)(_curved[_t1627]);
            uint16_t _141 = (uint16_t)(_curved[(_t1627 + 5152)]);
            uint8_t _142 = (uint8_t)(div_eucl(((_140 + _141) + 1), 2));
            uint16_t _143 = (uint16_t)(_142);
            uint16_t _144 = (uint16_t)(_curved[(_t1627 + 2576)]);
            uint8_t _145 = (uint8_t)(div_eucl(((_143 + _144) + 1), 2));
            uint16_t _146 = (uint16_t)(_145);
            uint16_t _147 = (uint16_t)(_curved[(_t1627 + 2)]);
            uint16_t _148 = (uint16_t)(_curved[(_t1627 + 5154)]);
            uint8_t _149 = (uint8_t)(div_eucl(((_147 + _148) + 1), 2));
            uint16_t _150 = (uint16_t)(_149);
            uint16_t _151 = (uint16_t)(_curved[(_t1627 + 2578)]);
            uint8_t _152 = (uint8_t)(div_eucl(((_150 + _151) + 1), 2));
            uint16_t _153 = (uint16_t)(_152);
            uint8_t _154 = (uint8_t)(div_eucl(((_146 + _153) + 1), 2));
            uint16_t _155 = (uint16_t)(_154);
            uint16_t _156 = (uint16_t)(_curved[(_t1627 + 1)]);
            uint16_t _157 = (uint16_t)(_curved[(_t1627 + 5153)]);
            uint8_t _158 = (uint8_t)(div_eucl(((_156 + _157) + 1), 2));
            uint16_t _159 = (uint16_t)(_158);
            uint16_t _160 = (uint16_t)(_t1628);
            uint8_t _161 = (uint8_t)(div_eucl(((_159 + _160) + 1), 2));
            uint16_t _162 = (uint16_t)(_161);
            uint8_t _163 = (uint8_t)(div_eucl(((_155 + _162) + 1), 2));
            int16_t _164 = (int16_t)(_163);
            int16_t _165 = (int16_t)(_sharpen_strength_x32[0]);
            int16_t _166 = (div_eucl(((_139 - _164) * _165), 32) + _139)<255 ? (div_eucl(((_139 - _164) * _165), 32) + _139) : 255;
            int16_t _167 = _166>0 ? _166 : 0;
            uint8_t _168 = (uint8_t)(_167);
            _processed[((_processed_s0_v2 * 4915200) + _t1669)] = _168;
           } // for _processed_s0_v2
          } // for _processed_s0_v0
         } // for _processed_s0_v1_v5
        } // for _processed_s0_v1_v3_v3
        free(_f3);
        free(_deinterleaved);
        free(_curved);
       } // alloc _curved
      } // alloc _deinterleaved
     } // alloc _f3
    } // for _processed_s0_v1_v3_v4
   } // alloc _sharpen_strength_x32
  } // alloc _f26
 } // alloc _curve
 return 0;
}

#ifdef __cplusplus
}  // extern "C"
#endif

